# score.py 1.0 generated by ADS 2.10.0
import os
import sys
from functools import lru_cache
from transformers import pipeline
import json
from typing import Dict, List
import numpy as np
from io import BytesIO
import base64
import logging
import torch


task = 'token-classification'

"""
   Inference script. This script is used for prediction by scoring server when schema is known.
"""

@lru_cache(maxsize=10)
def load_model(model_file_name=""):
    """
    Loads model from the serialized format

    Returns
    -------
    model:  a model instance on which predict API can be invoked.

    """
    model_dir = os.path.dirname(os.path.realpath(__file__))
    if model_dir not in sys.path:
        sys.path.insert(0, model_dir)

    try:
        
												  
        #john's fix to add ner aggregation_strategy
        #model = pipeline(task, model = model_dir)
        model = pipeline(task, model = model_dir, aggregation_strategy="first")
        
        print("Model is successfully loaded.")
    except Exception as e:
        raise Exception(f'Failed to load the model. ' + str(e))

    return model


def deserialize(data):
    """
    Deserialize json-serialized data to data in original type when sent to
predict.

    Parameters
    ----------
    data: serialized input data.

    Returns
    -------
    data: deserialized input data.

    """

    import cloudpickle
    from pickle import UnpicklingError
    deserialized_data = data
    try:
        deserialized_data = cloudpickle.loads(data)
    except TypeError:
        pass
    except UnpicklingError:
        logger.warning(
            "bytes are passed directly to the model. If the model expects a specific data format, you need to write the conversion logic in `deserialize()` yourself."
        )

    return deserialized_data



def pre_inference(data):
    """
    Preprocess json-serialized data to feed into predict function.

    Parameters
    ----------
    data: Data format as expected by the predict API of the core estimator.

    Returns
    -------
    data: Data format after any processing.

    """
    data = deserialize(data)

    # Add further data preprocessing if needed
    return data

def post_inference(yhat):
    """
    Post-process the model results.

    Parameters
    ----------
    yhat: Data format after calling model.predict.

    Returns
    -------
    yhat: Data format after any processing.

    """
    if isinstance(yhat, dict):
        return serialize_prediction(yhat)
    elif isinstance(yhat, list):
        serialized_yhat = []
        for yhat_i in yhat:
            serialized_yhat.append(serialize_prediction(yhat_i))
        return serialized_yhat
    elif isinstance(yhat, torch.Tensor):
        return yhat.tolist()

    if task == "conversational":
        raise NotImplementedError("The model output of task `conversational` is not json serializable. Add code here to populate json serializable output.")

    # Add further data postprocessing if needed
    return yhat


def serialize_prediction(yhat):
    """
    Serialize the values in the prediction.

    Parameters
    ----------
    yhat: model prediction.

    Returns
    -------
    yhat: Serialized model prediction.

    """
    
    if isinstance(yhat, dict):
        for key, value in yhat.items():
            if isinstance(value, torch.Tensor):
                yhat[key] = value.tolist()
            elif str(type(value)).startswith("<class 'PIL."):
                import PIL
                yhat[key] = np.asarray(value).tolist() if isinstance(value, PIL.Image.Image) else value
    
    #john's fix for the error "The inference result is not json parsable Object of type float32 is not JSON serializable" 
    if isinstance(yhat, dict):
        for key, value in yhat.items():
            if isinstance(value, np.float32):
                yhat[key] = float(value)

    return yhat


def validated_model_outputs(yhat):
    """
    Validates if the prediction is json serializable.

    Parameters
    ----------
    yhat: Prediction.

    Returns
    -------
    None

    Raises
    ------
    TypeError
        Type is not json serializable.

    """
    try:
        json.dumps(yhat)
    except:
        raise TypeError("The output is not json serializable.")


def predict(data, model=load_model()):
    """
    Returns prediction given the model and data to predict.

    Parameters
    ----------
    model: Model instance returned by load_model API
    data: Data format as expected by the predict API of the core estimator

    Returns
    -------
    predictions: Output from scoring server
        Format: {'prediction': output from model.predict method}

    """
    inputs = pre_inference(data)

    yhat = post_inference(
    model(**inputs) if isinstance(inputs, dict) else model(inputs)
    )
    validated_model_outputs(yhat)
    return {'prediction': yhat}